<a href="https://colab.research.google.com/github/reyzer223/pythonsemi/blob/main/semi_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('sample_data/california_housing_test.csv')

Задача №57. Решение в группах
1. Прочесть с помощью pandas файл
california_housing_test.csv, который находится в папке
sample_data
2. Посмотреть сколько в нем строк и столбцов
3. Определить какой тип данных имеют столбцы

In [ ]:
df.shape

(3000, 9)

In [ ]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

Задача №59. Решение в группах
1. Проверить есть ли в файле пустые значения
2. Показать median_house_value где median_income < 2
3. Показать данные в первых 2 столбцах
4. Выбрать данные где housing_median_age < 20 и
median_house_value > 70000

In [ ]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [ ]:
df[df['median_income'] < 2][['median_house_value','median_income']]

      median_house_value  median_income
5                67000.0         1.6635
6                67000.0         1.6641
16              181300.0         1.8750
28              350000.0         1.5830
43               79300.0         0.9838
...                  ...            ...
2943             57200.0         1.6563
2964             91300.0         1.1434
2985            109400.0         1.8633
2986             85400.0         1.1346
2995            225000.0         1.1790

[360 rows x 2 columns]

In [ ]:
df[['longitude','latitude']]

      longitude  latitude
0       -122.05     37.37
1       -118.30     34.26
2       -117.81     33.78
3       -118.36     33.82
4       -119.67     36.33
...         ...       ...
2995    -119.86     34.42
2996    -118.14     34.06
2997    -119.70     36.30
2998    -117.12     34.10
2999    -119.63     34.42

[3000 rows x 2 columns]

In [ ]:
df[(df['housing_median_age'] < 20) & (df['median_house_value'] > 70000)][['housing_median_age', 'median_house_value']]

      housing_median_age  median_house_value
4                   19.0             81700.0
7                   19.0            166900.0
8                   15.0            194400.0
13                  16.0            231200.0
16                  15.0            181300.0
...                  ...                 ...
2978                17.0            139700.0
2981                17.0            171300.0
2984                13.0            107000.0
2985                17.0            109400.0
2991                13.0            253800.0

[792 rows x 2 columns]

Задача №61. Решение в группах
1. Определить какое максимальное и минимальное
значение median_house_value
2. Показать максимальное median_house_value, где
median_income = 3.1250
3. Узнать какая максимальная population в зоне
минимального значения median_house_value

In [ ]:
print(df['median_house_value'].max())
print(df['median_house_value'].min())

500001.0
22500.0

In [ ]:
df[df['median_income'] == 3.1250]['median_house_value'].max()

233300.0

In [ ]:
df[df['median_house_value'] == df['median_house_value'].min()]['population'].max()

1230.0